### ISSUE TITLE
elm-live

### ISSUE THREAD

**Issue by mattiasw2** [rtfeldman/elm-spa-example#46]
Ubuntu 16.04

elm-live --output=elm.js src/Main.elm --pushstate --open --debug

gives. As you see below, I seem to have elm 0.18 properly working.

I can also start the project from within elm-reactor and click on Main.elm, but the it looks ugly, since the css are not loaded properly.

```
mattias@omen:~/data-oss/elm/elm-spa-example$ elm-live --output=elm.js src/Main.elm --pushstate --open --debug
/usr/local/lib/node_modules/elm-live/source/elm-live.js:165
  let serverStarted;
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-live/index.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
mattias@omen:~/data-oss/elm/elm-spa-example$ ls
assets  elm-package.json  elm-stuff  index.html  LICENSE  README.md  src  tests
mattias@omen:~/data-oss/elm/elm-spa-example$ elm-repl
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
```

**Comment by SidneyNemzer** [comment]
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Looks like you're running an older version of Node that doesn't support `let` (among other things). Try installing a newer version of Node.

**Comment by mattiasw2** [comment]
You are correct, the standard package for Ubuntu 16.04 is 4.2.3 or so. Upgraded to 8.11.1 and works fine.
